#!/usr/bin/env python3
"""NOS3-211 — inline the NOS3 coverage data + overlay into the standalone SPARTA
demo HTML so it stays a single self-contained file (booth/file:// friendly).

Idempotent: replaces the block between the NOS3_OVERLAY markers if present, else
inserts it right before </body>. Re-run after gen_nos3_coverage.py to refresh.

Run:
    python3 app/gen_nos3_coverage.py
    python3 app/build_overlay.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HTML = os.path.join(HERE, "sparta-standalone 1.html")
COVERAGE = os.path.join(HERE, "nos3_coverage.js")
OVERLAY = os.path.join(HERE, "nos3_overlay.js")

START = "<!-- NOS3_OVERLAY_START (generated by app/build_overlay.py) -->"
END = "<!-- NOS3_OVERLAY_END -->"


def main():
    for p in (HTML, COVERAGE, OVERLAY):
        if not os.path.exists(p):
            sys.exit(f"missing {p} (run gen_nos3_coverage.py first?)")

    html = open(HTML, encoding="utf-8").read()
    data_js = open(COVERAGE, encoding="utf-8").read()
    logic_js = open(OVERLAY, encoding="utf-8").read()

    block = (
        START + "\n"
        "<script>\n" + data_js + "\n</script>\n"
        "<script>\n" + logic_js + "\n</script>\n"
        + END
    )

    pat = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if pat.search(html):
        # Replacement passed as a function so backslash sequences in `block`
        # (e.g. Δ from JSON-escaped non-ASCII in the coverage data) are
        # inserted literally, not parsed as regex template escapes.
        html = pat.sub(lambda _m: block, html)
        action = "replaced"
    else:
        idx = html.rfind("</body>")
        if idx == -1:
            sys.exit("no </body> in HTML")
        html = html[:idx] + block + "\n" + html[idx:]
        action = "inserted"

    open(HTML, "w", encoding="utf-8").write(html)
    print(f"{action} NOS3 overlay block in {os.path.basename(HTML)} "
          f"({len(block)} bytes)")


if __name__ == "__main__":
    main()
