// AUTO-GENERATED by app/gen_nos3_coverage.py — do not edit by hand.
window.NOS3_COVERAGE_META = {
  "generated_from": [
    "V5_DETECTOR_COVERAGE.md",
    "incident_rescore.json",
    "cluster_taxonomy.json"
  ],
  "model": "iforest_per_mode_v5 + xgb_attack_classifier_v3",
  "incident_recall_headline": 0.6783,
  "n_techniques": 32
};
window.NOS3_COVERAGE = {
  "EX-0008.01": {
    "name": "ATS",
    "tier": "HIGH-VAR",
    "signal": "ON_BOARD",
    "frame_rate": 0.91,
    "incident_detected": 3,
    "incident_total": 3,
    "incident_recall": 1.0,
    "label_ok": 2,
    "cluster": "EX-0008.01"
  },
  "EX-0008.02": {
    "name": "RTS",
    "tier": "ROBUST",
    "signal": "ON_BOARD",
    "frame_rate": 0.91,
    "incident_detected": 3,
    "incident_total": 3,
    "incident_recall": 1.0,
    "label_ok": 3,
    "cluster": "EX-0008.02"
  },
  "EX-0012.03": {
    "name": "Memory write",
    "tier": "SIBLING",
    "signal": "ON_BOARD",
    "frame_rate": null,
    "incident_detected": 6,
    "incident_total": 6,
    "incident_recall": 1.0,
    "label_ok": 5,
    "cluster": "EX-0012.{03,04,05}"
  },
  "EX-0012.04": {
    "name": "App subscriber tables",
    "tier": "SIBLING",
    "signal": "ON_BOARD",
    "frame_rate": 0.63,
    "incident_detected": 5,
    "incident_total": 6,
    "incident_recall": 0.8333,
    "label_ok": 4,
    "cluster": "EX-0012.{03,04,05}"
  },
  "EX-0012.05": {
    "name": "Scheduling algorithm",
    "tier": "SIBLING",
    "signal": "ON_BOARD",
    "frame_rate": 0.64,
    "incident_detected": 6,
    "incident_total": 6,
    "incident_recall": 1.0,
    "label_ok": 4,
    "cluster": "EX-0012.{03,04,05}"
  },
  "EX-0012.07": {
    "name": "Propulsion subsystem",
    "tier": "HIGH-VAR",
    "signal": "ON_BOARD",
    "frame_rate": 1.0,
    "incident_detected": 4,
    "incident_total": 4,
    "incident_recall": 1.0,
    "label_ok": 2,
    "cluster": "EX-0012.07"
  },
  "EX-0012.08": {
    "name": "ADCS subsystem",
    "tier": "HIGH-VAR",
    "signal": "ON_BOARD",
    "frame_rate": 1.0,
    "incident_detected": 2,
    "incident_total": 3,
    "incident_recall": 0.6667,
    "label_ok": 2,
    "cluster": "EX-0012.08"
  },
  "EX-0012.09": {
    "name": "EPS subsystem",
    "tier": "HIGH-VAR",
    "signal": "ON_BOARD",
    "frame_rate": 0.99,
    "incident_detected": 3,
    "incident_total": 3,
    "incident_recall": 1.0,
    "label_ok": 3,
    "cluster": "EX-0012.09"
  },
  "EX-0012.12": {
    "name": "System clock",
    "tier": "SIBLING",
    "signal": "ON_BOARD",
    "frame_rate": 0.57,
    "incident_detected": 6,
    "incident_total": 6,
    "incident_recall": 1.0,
    "label_ok": 3,
    "cluster": "EX-0012.12/EX-0014.01"
  },
  "EX-0014.01": {
    "name": "Time spoof",
    "tier": "SIBLING",
    "signal": "ON_BOARD",
    "frame_rate": 0.26,
    "incident_detected": 6,
    "incident_total": 6,
    "incident_recall": 1.0,
    "label_ok": 5,
    "cluster": "EX-0012.12/EX-0014.01"
  },
  "EX-0014.03": {
    "name": "Sensor data spoof",
    "tier": "DEAD",
    "signal": "ON_BOARD",
    "frame_rate": 0.91,
    "incident_detected": 3,
    "incident_total": 3,
    "incident_recall": 1.0,
    "label_ok": 2,
    "cluster": "EX-0014.03"
  },
  "EX-0014.04": {
    "name": "PNT spoof",
    "tier": "HIGH-VAR",
    "signal": "ON_BOARD",
    "frame_rate": 0.98,
    "incident_detected": 3,
    "incident_total": 3,
    "incident_recall": 1.0,
    "label_ok": 3,
    "cluster": "EX-0014.04"
  },
  "IMP-0001": {
    "name": "Deception",
    "tier": "LOW-STABLE",
    "signal": "OBFUSCATION",
    "frame_rate": 0.61,
    "incident_detected": 3,
    "incident_total": 3,
    "incident_recall": 1.0,
    "label_ok": 2,
    "cluster": "IMP-0001"
  },
  "IMP-0002": {
    "name": "Disruption",
    "tier": "STABLE-MID",
    "signal": "ON_BOARD",
    "frame_rate": 0.58,
    "incident_detected": 3,
    "incident_total": 3,
    "incident_recall": 1.0,
    "label_ok": 3,
    "cluster": "IMP-0002"
  },
  "IMP-0003": {
    "name": "Denial",
    "tier": "STABLE-MID",
    "signal": "ON_BOARD",
    "frame_rate": 1.0,
    "incident_detected": 3,
    "incident_total": 3,
    "incident_recall": 1.0,
    "label_ok": 3,
    "cluster": "IMP-0003"
  },
  "IMP-0005": {
    "name": "Destruction",
    "tier": "ROBUST",
    "signal": "ON_BOARD",
    "frame_rate": 0.75,
    "incident_detected": 3,
    "incident_total": 3,
    "incident_recall": 1.0,
    "label_ok": 3,
    "cluster": "IMP-0005"
  },
  "IMP-0006": {
    "name": "Theft",
    "tier": "STABLE-MID",
    "signal": "UNSUBSCRIBED",
    "frame_rate": 0.62,
    "incident_detected": 3,
    "incident_total": 3,
    "incident_recall": 1.0,
    "label_ok": 3,
    "cluster": "IMP-0006"
  },
  "DE-0003.01": {
    "name": "Vehicle command counter",
    "tier": "ROBUST",
    "signal": "OBFUSCATION",
    "frame_rate": null,
    "incident_detected": 0,
    "incident_total": 3,
    "incident_recall": 0.0,
    "label_ok": 0,
    "cluster": "DE-0003.01"
  },
  "DE-0003.02": {
    "name": "Rejected command counter",
    "tier": "LOW-STABLE",
    "signal": "OBFUSCATION",
    "frame_rate": null,
    "incident_detected": 0,
    "incident_total": 3,
    "incident_recall": 0.0,
    "label_ok": 0,
    "cluster": "DE-0003.02"
  },
  "DE-0003.03": {
    "name": "Command receiver mode",
    "tier": "DEAD",
    "signal": "UNSUBSCRIBED",
    "frame_rate": null,
    "incident_detected": 1,
    "incident_total": 3,
    "incident_recall": 0.3333,
    "label_ok": 0,
    "cluster": "DE-0003.03"
  },
  "DE-0003.06": {
    "name": "Telemetry downlink modes",
    "tier": "DEAD",
    "signal": "ON_BOARD",
    "frame_rate": null,
    "incident_detected": 0,
    "incident_total": 3,
    "incident_recall": 0.0,
    "label_ok": 0,
    "cluster": "DE-0003.06"
  },
  "DE-0003.08": {
    "name": "Received commands",
    "tier": "DEAD",
    "signal": "OBFUSCATION",
    "frame_rate": null,
    "incident_detected": 0,
    "incident_total": 3,
    "incident_recall": 0.0,
    "label_ok": 0,
    "cluster": "DE-0003.08"
  },
  "DE-0003.09": {
    "name": "System clock for evasion",
    "tier": "DEAD",
    "signal": "ON_BOARD",
    "frame_rate": null,
    "incident_detected": 3,
    "incident_total": 4,
    "incident_recall": 0.75,
    "label_ok": 3,
    "cluster": "DE-0003.09"
  },
  "DE-0003.10": {
    "name": "GPS ephemeris",
    "tier": "ROBUST",
    "signal": "ON_BOARD",
    "frame_rate": null,
    "incident_detected": 3,
    "incident_total": 3,
    "incident_recall": 1.0,
    "label_ok": 3,
    "cluster": "DE-0003.10"
  },
  "EX-0001.01": {
    "name": "Command packets",
    "tier": "OUT-OF-SCOPE",
    "signal": "CONCEPTUAL",
    "frame_rate": null,
    "incident_detected": 0,
    "incident_total": 3,
    "incident_recall": 0.0,
    "label_ok": 0,
    "cluster": null
  },
  "EX-0009.01": {
    "name": "Flight software",
    "tier": "OUT-OF-SCOPE",
    "signal": "CONCEPTUAL",
    "frame_rate": null,
    "incident_detected": 0,
    "incident_total": 3,
    "incident_recall": 0.0,
    "label_ok": 0,
    "cluster": null
  },
  "IMP-0004": {
    "name": "Degradation",
    "tier": "OUT-OF-SCOPE",
    "signal": "CONCEPTUAL",
    "frame_rate": null,
    "incident_detected": 0,
    "incident_total": 3,
    "incident_recall": 0.0,
    "label_ok": 0,
    "cluster": null
  },
  "DE-0003.04": {
    "name": "Command receiver RSSI",
    "tier": "OUT-OF-SCOPE",
    "signal": "CONCEPTUAL",
    "frame_rate": null,
    "incident_detected": null,
    "incident_total": null,
    "incident_recall": null,
    "label_ok": null,
    "cluster": null
  },
  "DE-0003.05": {
    "name": "Command receiver lock modes",
    "tier": "OUT-OF-SCOPE",
    "signal": "CONCEPTUAL",
    "frame_rate": null,
    "incident_detected": 0,
    "incident_total": 1,
    "incident_recall": 0.0,
    "label_ok": 0,
    "cluster": null
  },
  "DE-0003.07": {
    "name": "Cryptographic modes",
    "tier": "OUT-OF-SCOPE",
    "signal": "CONCEPTUAL",
    "frame_rate": null,
    "incident_detected": 0,
    "incident_total": 3,
    "incident_recall": 0.0,
    "label_ok": 0,
    "cluster": null
  },
  "DE-0003.11": {
    "name": "Watchdog timer",
    "tier": "OUT-OF-SCOPE",
    "signal": "UNSUBSCRIBED",
    "frame_rate": null,
    "incident_detected": 0,
    "incident_total": 3,
    "incident_recall": 0.0,
    "label_ok": 0,
    "cluster": null
  },
  "DE-0003.12": {
    "name": "Poison AI/ML training",
    "tier": "OUT-OF-SCOPE",
    "signal": "CONCEPTUAL",
    "frame_rate": null,
    "incident_detected": 0,
    "incident_total": 1,
    "incident_recall": 0.0,
    "label_ok": 0,
    "cluster": null
  }
};
